### ISSUE TITLE
Spanish inflector not working

### ISSUE THREAD

**Issue by demian85** [martinandert/inflected#3]
```
var Inflector = require('inflected');

console.log(Inflector.singularize('arroces', 'es'));
console.log(Inflector.singularize('autos', 'es'));
console.log(Inflector.singularize('veganos', 'es'));
```

Outputs the same input!

**Comment by martinandert** [comment]
Hi @demian85, that's because the inflector supports only English rules out of the box.

But you can easily add rules (perhaps in a config file that's loaded on start up) that are relevant to your language / application like this:

```js
function enDefaults(inflect) {
  inflect.plural(/* ... */);
  inflect.plural(/* ... */);
  inflect.singular(/* ... */);
  inflect.irregular(/* ... */);
  inflect.uncountable(/* ... */);
}

Inflector.inflections('es', esRules);
```

See https://github.com/martinandert/inflected/blob/master/lib/defaults.js for all defined English language rules.
