### ISSUE TITLE
Add Constantize Feature

### ISSUE THREAD

**Issue by davidonlaptop** [martinandert/inflected#6]
Good work guys!

ActiveSupport has a constantize method that turns an input into a CONSTANT_CASE.

If you're interested in the feature, I can look if I find time to contribute it.

**Comment by martinandert** [comment]
Hey David, ActiveSupport's `constantize` method doesn't actually transform a string like you described. It rather tries to find and return a declared constant with the name specified in the string. Since that's not readily doable in JS, I didn't port `constantize` in the first place.

Nevertheless I do think your idea would be a great addition. So please go for it!

**Comment by davidonlaptop** [comment]
There it is.

I've named the function toConstantCase to avoid confusion with rails's constantize. I've found this useful when generating names for redux saga actions.
